# automatic testing with Travis CI!

language: node_js

node_js:
  - "node"

before_script:
  - npm install -g selenium-side-runner
  - npm install -g chromedriver

script:
  - node index.js & npm run test
