# automatic testing with Travis CI!

language:
  - node_js
  - python

node_js:
  - "11"

python:
  - "3.7"

addons:
  chrome: stable

cache:
  npm: true
  directories:
    - node_modules

before_script:
  - npm install -g chromedriver
  - npm install -g selenium-side-runner

script:
  # - python run_python_too.py & node index.js & selenium-side-runner -c "goog:chromeOptions.args=[--headless,--nogpu] browserName=chrome" test.side; pkill -9 -f run_python_too.py; killall -9 node
  - npm run test
