# automatic testing with Travis CI!

sudo: required

language: node_js

node_js:
  - "node"

before_script:
  - npm install -g selenium-side-runner
  - npm install -g chromedriver
  - export CHROME_BIN=/usr/bin/google-chrome

script:
  - node index.js & npm run test
