# automatic testing with Travis CI!

language: node_js

node_js:
  - "11"

addons:
  chrome: stable

cache:
  npm: true
  directories:
    - node_modules

before_script:
  - npm install -g chromedriver
  - npm install -g selenium-side-runner

script:
  # - node index.js & selenium-side-runner -c "goog:chromeOptions.args=[--headless,--nogpu] browserName=chrome" test.side; killall -9 node
  - npm run test
