# automatic testing with Travis CI!

language:
  - node_js
  - python

node_js:
  - "11"

python:
  - "3.7"

addons:
  chrome: stable

cache:
  # npm: true
  yarn: true
  directories:
    - node_modules

before_script:
  # - npm install -g chromedriver
  # - npm install -g selenium-side-runner
  - yarn add chromedriver
  - yarn add selenium-side-runner

script:
  # - python3 run_python_too.py & node index.js & selenium-side-runner -c "goog:chromeOptions.args=[--headless,--nogpu] browserName=chrome" test.side; # killall -9 node; # pkill -9 -f run_python_too.py;
  - yarn test

notifications:
  email:
    # If you don't want to specify emails here,
    # you can set your email with git config --global user.email
    on_success: change
    on_failure: always
