# automatic testing with Travis CI!

language: node_js

node_js:
  - "node"

before_script:
  - npm install -g selenium-side-runner
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
  - export CHROME_BIN=chromium-browser

script:
  - node index.js & npm run test
