language: node_js
node_js:
  - "7"
dist: trusty
sudo: required
addons:
  chrome: stable
install:
  - npm install
  - npm install -g selenium-side-runner
  - npm install -g chromedriver
script:
  - node index.js & npm run test
